name: CI Pipeline
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -x test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      # 중요: 여기서는 latest 태그만 사용
      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ steps.timestamp.outputs.timestamp }}
      - name: Checkout infrastructure repository
        uses: actions/checkout@v3
        with:
          repository: TP1-OuterMSA/msa-infra
          path: msa-infra
          token: ${{ secrets.GH_PAT }}
      # 디버깅을 위한 단계 추가
      - name: Verify directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "msa-infra directory contents:"
          ls -la msa-infra
          echo "charts directory contents:"
          ls -la msa-infra/charts
          echo "services directory contents:"
          ls -la msa-infra/charts/services
          echo "msa-test2 directory contents:"
          ls -la msa-infra/charts/services/msa-test2
      - name: Update image tag in Helm chart
        run: |
          cd msa-infra/charts/services/msa-test2
          # values.yaml 파일 내용 확인
          echo "Current values.yaml content:"
          cat values.yaml
          # 타임스탬프 태그로 설정
          sed -i "s/tag: \".*\"/tag: \"${{ steps.timestamp.outputs.timestamp }}\"/g" values.yaml
          # 변경 후 확인
          echo "Updated values.yaml content:"
          cat values.yaml
      - name: Commit and push changes to infrastructure repo
        run: |
          cd msa-infra
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          # 변경사항이 있을 때만 커밋 시도
          git diff-index --quiet HEAD || git commit -m "Update msa-test2 image tag"
          # 변경사항이 없어도 에러로 처리하지 않음
          git push || echo "No changes to push"
